# Generated by Django 5.2.6 on 2025-09-25 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original', models.TextField()),
                ('drug', models.CharField(blank=True, max_length=100)),
                ('adverse_events', models.TextField(blank=True)),
                ('severity', models.CharField(blank=True, max_length=50)),
                ('outcome', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
